$background = rgb({{background | replace("#", "")}})
$foreground = rgb({{foreground | replace("#", "")}})
$color0 = rgb({{color0 | replace("#", "")}})
$color1 = rgb({{color1 | replace("#", "")}})
$color2 = rgb({{color2 | replace("#", "")}})
$color3 = rgb({{color3 | replace("#", "")}})
$color4 = rgb({{color4 | replace("#", "")}})
$color5 = rgb({{color5 | replace("#", "")}})
$color6 = rgb({{color6 | replace("#", "")}})
$color7 = rgb({{color7 | replace("#", "")}})
$color8 = rgb({{color8 | replace("#", "")}})
$color9 = rgb({{color9 | replace("#", "")}})
$color10 = rgb({{color10 | replace("#", "")}})
$color11 = rgb({{color11 | replace("#", "")}})
$color12 = rgb({{color12 | replace("#", "")}})
$color13 = rgb({{color13 | replace("#", "")}})
$color14 = rgb({{color14 | replace("#", "")}})
$color15 = rgb({{color15 | replace("#", "")}})
