# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = notify-send "Locking..."   # This is a placeholder, it will not run
    unlock_cmd = notify-send "Unlocked!" # This is a placeholder
    ignore_dbus_inhibit = false          # Recommended to keep false
}

# Turn off monitors after 15 minutes
listener {
    timeout = 900                                # 15 minutes
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on; systemctl --user restart waybar.service
}
