context.modules = [
{   name = libpipewire-module-filter-chain
    args = {
        node.description = "MMX 330 (Denoised)"
        media.name       = "MMX 330 (Denoised)"
        filter.graph = {
            nodes = [
                {
                    type   = ladspa
                    name   = rnnoise
                    # The specific library name provided by the package
                    plugin = "/usr/lib/ladspa/librnnoise_ladspa.so"
                    # The internal label for the mono plugin
                    label  = "noise_suppressor_mono"
                    control = {
                        "VAD Threshold (%)" = 50.0
                        "VAD Grace Period (ms)" = 200
                        "Retroactive VAD Grace (ms)" = 0
                    }
                }
            ]
        }
        capture.props = {
            node.passive = true
            audio.rate = 48000
        }
        playback.props = {
            media.class = Audio/Source
        }
    }
}
]
